// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ14dEbcvSfGdGEcF-xH8DMsp3pJbLZ0c',
    appId: '1:806710041554:ios:914abbceee1c8d6279060b',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    storageBucket: 'joybank-9636f.firebasestorage.app',
    iosBundleId: 'com.sedev.com.kiosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ14dEbcvSfGdGEcF-xH8DMsp3pJbLZ0c',
    appId: '1:806710041554:ios:914abbceee1c8d6279060b',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    storageBucket: 'joybank-9636f.firebasestorage.app',
    iosBundleId: 'com.sedev.com.kiosk',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSo6JNCqsOdF6rC9DRsU72FyK9rwHgD1E',
    appId: '1:806710041554:web:ca594e35c4ea894479060b',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    authDomain: 'joybank-9636f.firebaseapp.com',
    storageBucket: 'joybank-9636f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NFAxP-t8Rhoj1UPsk0prQkLbiJKj9fw',
    appId: '1:806710041554:android:d3eaaea8873b2e8279060b',
    messagingSenderId: '806710041554',
    projectId: 'joybank-9636f',
    storageBucket: 'joybank-9636f.firebasestorage.app',
  );

}